---
title: "The Forbes Billionaires"
author: "Seyram A. Butame"
format: 
  html:
    toc: true
    code-fold: true
    code-overflow: wrap
    css: styles.css
  pdf: default
bibliography: https://api.citedrive.com/bib/94ea4ce6-0d99-4cf2-9f69-7ac984099349/references.bib?x=eyJpZCI6ICI5NGVhNGNlNi0wZDk5LTRjZjItOWY2OS03YWM5ODQwOTkzNDkiLCAidXNlciI6ICIxOTAyIiwgInNpZ25hdHVyZSI6ICI1YjQyYWJhMGJjN2EwZDRkZGJhNjJjNjAyNTVlODljYzNmMWYyOTYyODMzN2E0YWViYzViYTExNGU5NjYzZTUxIn0=/bibliography.bib
csl: nature.csl
editor: source
---

## Libraries

I will be using the following packages:

1. `tidyverse` -- For basic data wrangling.[@2019Wickham-td]
2.  `janitor` -- I sometimes use this package for data cleaning and data tabulation. However, I do prefer to use `dplyr` (which is part of the tidyverse) when I can.[@2023Firke-jw]
3. `showtext` -- Helps with using certain fonts with ggplot.[@2022Qiu-px]
4. `ggpattern` -- Allows for patterened geoms within ggplot (think adding pictures and images to bars in a chart).[@2022FC_Davis-gg] 

```{R, lib, messag=FALSE, warning=FALSE}

library(tidyverse)
library(janitor)
library(ggpattern)
library(showtext)
library(ggpattern)
```


```{R, data, message=FALSE, warning=FALSE}

font_add_google("Roboto", "regular")
showtext_auto()


df1 <- read_csv("data/forbesbillons.csv")

Bernard_Arnault_and_Family <- "https://upload.wikimedia.org/wikipedia/commons/d/de/Bernard_Arnault_%283%29_-_2017_%28cropped%29.jpg"
Elon_Musk <- "https://upload.wikimedia.org/wikipedia/commons/9/93/Elon_Musk_Colorado_2022_%28cropped%29.jpg"
Jeff_Bezos <- "https://upload.wikimedia.org/wikipedia/commons/3/33/Jeff_Bezos_2016.jpg"
Larry_Ellison <- "https://upload.wikimedia.org/wikipedia/commons/0/00/Larry_Ellison_picture.png"
Warren_Buffet <- "https://upload.wikimedia.org/wikipedia/commons/d/d4/Warren_Buffett_at_the_2015_SelectUSA_Investment_Summit_%28cropped%29.jpg"
Bill_gates <- "https://upload.wikimedia.org/wikipedia/commons/f/f9/Bill_Gates_%282020%29_01.jpg"
Michael_Bloomberg <- "https://media.vanityfair.com/photos/5bfc230249a5732cd95df343/master/w_2560%2Cc_limit/l-Wall-Street-Pro-Bloomberg.jpg"
Carlos_Slim_Helu_and_Family <- "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Carlos_Slim_2012.jpg/1200px-Carlos_Slim_2012.jpg"
Mukesh_Ambani <- "https://vz.cnwimg.com/wp-content/uploads/2013/11/GettyImages-187455378.jpg"
Steve_Ballmer <- "https://myce.wiki/wp-content/images_posts/2017/05/Steve_Ballmer_at_CES_2010_cropped.jpg"

p1 <- df1 %>%
  ggplot(aes(reorder(billionaire, -worth), 
             worth, pattern_filename = as.factor(worth))) +
  geom_col_pattern(pattern = "image",
    color = "black",
    alpha = 0.8,
    pattern_type = "expand"
  ) +
  scale_pattern_filename_manual(
    values = c(`211` = Bernard_Arnault_and_Family, `180` = Elon_Musk, `114` = Jeff_Bezos, `107` = Larry_Ellison, `106` = Warren_Buffet, `104` = Bill_gates, `94.5` = Michael_Bloomberg, `93` = Carlos_Slim_Helu_and_Family, `83.4` = Mukesh_Ambani, `80.7` = Steve_Ballmer)) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))+
  scale_y_continuous(labels = function(x) paste0("$", x, "B"))+
  annotate("text", x=6.5, y=180, label= "Forbes Billionaires", color = '#663333', size = 10, family = 'Roboto', fontface = "bold")+
  annotate("text", x=7, y=150, label= "The Richest in 2023", color = '#117b9e', size = 8, family = 'Roboto', fontface = "bold")+
  theme_minimal() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(size = 8, face = "bold", family = "rubik",color = '#117b9e'))+
  theme(axis.text.y = element_text(size = 8, face = "bold",family = "rubik",color = '#117b9e'))+
  theme(axis.title.x = element_blank())+
  theme(axis.title.y = element_blank())+
  theme(plot.background  = element_rect(fill="#FDFAF1", color="#FDFAF1"))

p1

```

## Image Sources

-  Bernard Arnault - <a href="https://commons.wikimedia.org/wiki/File:Bernard_Arnault_(3)_-_2017_(cropped).jpg#/media/File:Bernard_Arnault_(3)_-_2017_(cropped).jpg">Conference at the Ecole polytechnique of Bernard Arnault "LVMH: construction of a worldwide French leader" - **Jérémy Barande** (Ecole polytechnique Université Paris-Saclay)</a>

- Elon Musk - <a href="https://upload.wikimedia.org/wikipedia/commons/9/93/Elon_Musk_Colorado_2022_%28cropped%29.jpg">U.S. Air Force Academy, Colorado -- by **Trevor Cokley**</a>

- Jeff Bezos - <a href="https://upload.wikimedia.org/wikipedia/commons/3/33/Jeff_Bezos_2016.jpg">Bezos at the U.S. Department of Defense-- by Senior Master Sgt. Adrian Cadiz</a>


